#!/bin/sh

if [ ! -f .initialized ]; then
	# Container is initialized according the environment variables
	# passed to the container to setup the application.
	/usr/local/bin/setup-container
fi

/usr/local/sbin/runsvdir-init
